name: DocC Publishing

on:
  release:
    types: [published]
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.2.0"
      # Enable the swift-docc-plugin dependency  
      # sed -i '' 's|//\.package(url: "https://github.com/swiftlang/swift-docc-plugin", from: "1.1.0"),|.package(url: "https://github.com/swiftlang/swift-docc-plugin", from: "1.1.0"),|' Package.swift
      - name: Generate Documentation
        run: |
          # Pretty print DocC JSON output so that it can be consistently diffed between commits
          export DOCC_JSON_PRETTYPRINT="YES"

          # Create docs directory
          mkdir -p ./docs

          # Generate documentation
          swift package \
            --allow-writing-to-directory ./docs \
            generate-documentation \
            --target SwiftChance \
            --disable-indexing \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path swift-chance
      # - name: Select Xcode version
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: latest-stable
      # - name: Build DocC
      #   run: |
      #     xcodebuild docbuild \
      #       -scheme SwiftChance \
      #       -configuration Release \
      #       -derivedDataPath tmp/doc \
      #       -destination 'platform=macOS'
      # - name: Process DocC into HTML
      #   run: |
      #     $(xcrun -f docc) process-archive \
      #       transform-for-static-hosting $(find tmp/doc -type d -name 'SwiftChance.doccarchive') \
      #       --output-path docs/ \
      #       --hosting-base-path martoniojunior.github.io/SwiftChance/;

      #     echo "<script>window.location.href += \"/documentation/swiftchance\"</script>" > docs/index.html;
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4